### ISSUE TITLE
питон язык для обезьян

### ISSUE THREAD

**Issue by MahadRegent** [xi816/GovnOS#2]
используйте джаву или C++ 

Почему все пишут на питоне? Он же ломаеться с каждой новой версией , и для каждого проекта нужно выбрать версию этого тупого питона, на которой он написан. 

Почему не C , C++ , или джава?

**Comment by Danetterry** [comment]
Для этой программы удобнее использовать скриптовые языки, так как это тупа скрипт который симулирует ос. Использование низкоуровленых языков принесло бы лишь лишний геморой.

А что у нас по скриптовым языкам?
**Джиес**, который понятное дело тут не подойдёт 
**Луа**, в котором почти ничего встроенного нет
**Баш**, с которым симулятор не запустится под виндой
И **питон**, который идеально тут подходит

> Он же ломаеться с каждой новой версией , и для каждого проекта нужно выбрать версию этого тупого питона, на которой он написан.

use conda

**Comment by xi816** [comment]
он не симулирует, а эмулирует. под шринду он и так не запустится, кстати.
там свой процессор

**Comment by Danetterry** [comment]
Эмуляция это если бы у тебя был бы эмулятор по типу pico-8, в данном случае эмуляции тут нет, как и процессора

**Comment by xi816** [comment]
@Danetterry https://github.com/xi816/cgovnos, аот эмулятор на C
